substitutions:
  _REGION: asia-south1
  _REPOSITORY: taskora
  _WEB_SERVICE: taskora-web
  _API_SERVICE: taskora-api
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "--target",
        "web",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web:${SHORT_SHA}",
        ".",
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "--target",
        "api",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api:${SHORT_SHA}",
        ".",
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web:${SHORT_SHA}",
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api:${SHORT_SHA}",
      ]
images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web:${SHORT_SHA}"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api:${SHORT_SHA}"
options:
  logging: CLOUD_LOGGING_ONLY
